name: Playwright and Synpress Tests Scheduled

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    - cron: "*/5 * * * *" # Triggers the workflow every 5 minutes

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies #1
        run: yarn install
        working-directory: ./app-next

      - name: Install dependencies #2
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step to build the cache for Synpress
      - name: Build Synpress cache
        run: xvfb-run npx synpress ./tests/

      # Run Playwright tests (headful mode)
      - name: Run E2E tests (Playwright headful)
        run: xvfb-run yarn playwright test ./tests/multisig-plugin/02_publishProposal.spec.ts --project=chromium
        continue-on-error: true
        # run: xvfb-run npx playwright test --list

      # Optionally, upload the test results for review
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
