name: Playwright and Synpress Tests on Schedule

on:
  schedule:
    - cron: "*/5 * * * *" # This cron expression triggers the workflow every 5 minutes

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App-Next Repository
        uses: actions/checkout@v4
        with:
          # Points to the external repository
          repository: aragon/app-next
          # Use the latest code in the develop branch
          ref: develop

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies for App-Next
        run: yarn install

      - name: Install dependencies for E2E
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Synpress cache
        run: xvfb-run npx synpress ./tests/

      - name: Run E2E tests (Playwright headful)
        run: xvfb-run yarn playwright test ./tests/multisig-plugin/02_publishProposal.spec.ts --project=chromium
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
