name: Playwright and Synpress Tests for PRs and Pushes

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App-Next Repository
        uses: actions/checkout@v4
        with:
          # Points to the external repository
          repository: aragon/app-next
          # Use the pull request head ref for PR events, otherwise use the push ref
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ secrets.APP_NEXT_ACCESS_TOKEN }}
          # token: ${{ secrets.GITHUB_TOKEN }} # Not required for public repos, but recommended for dispatch events

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies for App-Next
        run: yarn install

      - name: Install dependencies for E2E
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Synpress cache
        run: xvfb-run npx synpress ./tests/

      - name: Run E2E tests (Playwright headful)
        run: xvfb-run yarn playwright test ./tests/multisig-plugin/02_publishProposal.spec.ts --project=chromium
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
